#!/bin/bash

export PATH=/var/vcap/packages/ruby/bin:$PATH

RUN_DIR=/var/vcap/sys/run/ping_gateway
LOG_DIR=/var/vcap/sys/log/ping_gateway
PIDFILE=$RUN_DIR/ping_gateway.pid

JOB_DIR=/var/vcap/jobs/ping_gateway

source /var/vcap/packages/common/utils.sh

case $1 in

  start)
    pid_guard $PIDFILE "Ping gateway"

    mkdir -p $RUN_DIR
    mkdir -p $LOG_DIR

    echo $$ > $PIDFILE

    <% if properties.syslog_aggregator %>
    /var/vcap/packages/syslog_aggregator/setup_syslog_forwarder.sh $JOB_DIR/config
    <% end %>

    exec /var/vcap/packages/ping_gateway/services/PingSvc/bin/ping_gateway \
         -c $JOB_DIR/config/ping_gateway.yml \
         >>$LOG_DIR/ping_gateway.stdout.log \
         2>>$LOG_DIR/ping_gateway.stderr.log

    ;;

  stop)
    kill_and_wait $PIDFILE

    ;;

  *)
    echo "Usage: ping_gateway_ctl {start|stop}"

    ;;

esac
